### ISSUE TITLE
extunix dependency can be replaced by tuntap

### ISSUE THREAD

**Issue by avsm** [haesbaert/hdhcp#1]
The https://github.com/mirage/ocaml-tuntap exposes `getifaddrs` that is parsed into an `Ipaddr.t` already.  That would remove Extunix with a smaller library in the form of `tuntap` in `config_parser.ml`

**Comment by haesbaert** [comment]
Yep, we could do that, but I've started rewriting extunix's recvmsg to be able to have multiple ancillary control options, basically I need IP_RECVIF in bsds and PKTINFO in linux. Extunix doesn't use ctypes which makes it kinda painful.

**Comment by avsm** [comment]
Yeah binding to them directly in a minilibrary with ctypes makes life *much* easier from a mirage perspective.

**Comment by haesbaert** [comment]
I can reconsider this, it seemed more logical at first to add to an existing library.

**Comment by haesbaert** [comment]
The dependency can now go away as I've written my own recvmsg wrapper, so won't rely on my future work on extunix.

**Comment by haesbaert** [comment]
Replaced extunix with ocaml-tuntap, that pull-request I made is necessary though.
